require('dotenv').config({ path: __dirname + '/../.env' });
const mongoose = require('mongoose');
const ResultSource = require('../models/ResultSource');

const boardData = [
  // National Boards
  {
    name: 'CBSE Class 10 Results',
    board: 'CBSE',
    state: '',
    level: '10',
    examName: 'Central Board of Secondary Education - Secondary School Examination',
    url: 'https://results.cbse.nic.in',
    description: 'Official portal for CBSE Class 10th Board Exam results.',
  },
  {
    name: 'CBSE Class 12 Results',
    board: 'CBSE',
    state: '',
    level: '12',
    examName: 'Central Board of Secondary Education - Senior School Certificate Examination',
    url: 'https://results.cbse.nic.in',
    description: 'Official portal for CBSE Class 12th Board Exam results.',
  },
  {
    name: 'ICSE Class 10 Results',
    board: 'ICSE',
    state: '',
    level: '10',
    examName: 'Council for the Indian School Certificate Examinations - ICSE',
    url: 'https://results.cisce.org',
    description: 'Official portal for ICSE Class 10th results.',
  },
  {
    name: 'ISC Class 12 Results',
    board: 'ICSE',
    state: '',
    level: '12',
    examName: 'Council for the Indian School Certificate Examinations - ISC',
    url: 'https://results.cisce.org',
    description: 'Official portal for ISC Class 12th results.',
  },
  {
    name: 'NIOS Secondary Class 10 Results',
    board: 'Other',
    state: '',
    level: '10',
    examName: 'National Institute of Open Schooling - Secondary Examination',
    url: 'https://results.nios.ac.in',
    description: 'Official portal for NIOS Class 10th results.',
  },
  {
    name: 'NIOS Sr. Secondary Class 12 Results',
    board: 'Other',
    state: '',
    level: '12',
    examName: 'National Institute of Open Schooling - Senior Secondary Examination',
    url: 'https://results.nios.ac.in',
    description: 'Official portal for NIOS Class 12th results.',
  },

  // State Boards
  {
    name: 'UP Board Class 10 High School Results',
    board: 'State',
    state: 'Uttar Pradesh',
    level: '10',
    examName: 'Board of High School and Intermediate Education Uttar Pradesh',
    url: 'https://upresults.nic.in',
    description: 'Official portal for UP Board Class 10th results.',
  },
  {
    name: 'UP Board Class 12 Intermediate Results',
    board: 'State',
    state: 'Uttar Pradesh',
    level: '12',
    examName: 'Board of High School and Intermediate Education Uttar Pradesh',
    url: 'https://upresults.nic.in',
    description: 'Official portal for UP Board Class 12th results.',
  },
  {
    name: 'Bihar Board Matric Class 10 Results',
    board: 'State',
    state: 'Bihar',
    level: '10',
    examName: 'Bihar School Examination Board - Matriculation',
    url: 'https://results.biharboardonline.com',
    description: 'Official portal for BSEB Class 10th results.',
  },
  {
    name: 'Bihar Board Intermediate Class 12 Results',
    board: 'State',
    state: 'Bihar',
    level: '12',
    examName: 'Bihar School Examination Board - Intermediate',
    url: 'https://results.biharboardonline.com',
    description: 'Official portal for BSEB Class 12th results.',
  },
  {
    name: 'Maharashtra Board SSC Class 10 Results',
    board: 'State',
    state: 'Maharashtra',
    level: '10',
    examName: 'Maharashtra State Board of Secondary & Higher Secondary Education - SSC',
    url: 'https://mahresult.nic.in',
    description: 'Official portal for Maharashtra Class 10th results.',
  },
  {
    name: 'Maharashtra Board HSC Class 12 Results',
    board: 'State',
    state: 'Maharashtra',
    level: '12',
    examName: 'Maharashtra State Board of Secondary & Higher Secondary Education - HSC',
    url: 'https://mahresult.nic.in',
    description: 'Official portal for Maharashtra Class 12th results.',
  },
  {
    name: 'Rajasthan Board Secondary Class 10 Results',
    board: 'State',
    state: 'Rajasthan',
    level: '10',
    examName: 'Board of Secondary Education Rajasthan - Secondary',
    url: 'https://rajeduboard.rajasthan.gov.in',
    description: 'Official portal for BSER Class 10th results.',
  },
  {
    name: 'Rajasthan Board Sr. Secondary Class 12 Results',
    board: 'State',
    state: 'Rajasthan',
    level: '12',
    examName: 'Board of Secondary Education Rajasthan - Senior Secondary',
    url: 'https://rajeduboard.rajasthan.gov.in',
    description: 'Official portal for BSER Class 12th results.',
  },
  {
    name: 'MP Board High School Class 10 Results',
    board: 'State',
    state: 'Madhya Pradesh',
    level: '10',
    examName: 'Board of Secondary Education Madhya Pradesh - High School',
    url: 'https://mpresults.nic.in',
    description: 'Official portal for MPBSE Class 10th results.',
  },
  {
    name: 'MP Board Higher Secondary Class 12 Results',
    board: 'State',
    state: 'Madhya Pradesh',
    level: '12',
    examName: 'Board of Secondary Education Madhya Pradesh - Higher Secondary',
    url: 'https://mpresults.nic.in',
    description: 'Official portal for MPBSE Class 12th results.',
  },
  {
    name: 'Punjab Board Matric Class 10 Results',
    board: 'State',
    state: 'Punjab',
    level: '10',
    examName: 'Punjab School Education Board - Matriculation',
    url: 'https://www.pseb.ac.in/results',
    description: 'Official portal for PSEB Class 10th results.',
  },
  {
    name: 'Punjab Board Sr. Secondary Class 12 Results',
    board: 'State',
    state: 'Punjab',
    level: '12',
    examName: 'Punjab School Education Board - Senior Secondary',
    url: 'https://www.pseb.ac.in/results',
    description: 'Official portal for PSEB Class 12th results.',
  },
  {
    name: 'Haryana Board Secondary Class 10 Results',
    board: 'State',
    state: 'Haryana',
    level: '10',
    examName: 'Board of School Education Haryana - Secondary',
    url: 'https://bseh.org.in/all-results',
    description: 'Official portal for HBSE Class 10th results.',
  },
  {
    name: 'Haryana Board Sr. Secondary Class 12 Results',
    board: 'State',
    state: 'Haryana',
    level: '12',
    examName: 'Board of School Education Haryana - Senior Secondary',
    url: 'https://bseh.org.in/all-results',
    description: 'Official portal for HBSE Class 12th results.',
  },
  {
    name: 'Jharkhand Board Matric Class 10 Results',
    board: 'State',
    state: 'Jharkhand',
    level: '10',
    examName: 'Jharkhand Academic Council - Matriculation',
    url: 'https://jacresults.com',
    description: 'Official portal for JAC Class 10th results.',
  },
  {
    name: 'Jharkhand Board Intermediate Class 12 Results',
    board: 'State',
    state: 'Jharkhand',
    level: '12',
    examName: 'Jharkhand Academic Council - Intermediate',
    url: 'https://jacresults.com',
    description: 'Official portal for JAC Class 12th results.',
  },
  {
    name: 'Gujarat Board SSC Class 10 Results',
    board: 'State',
    state: 'Gujarat',
    level: '10',
    examName: 'Gujarat Secondary and Higher Secondary Education Board - SSC',
    url: 'https://www.gseb.org',
    description: 'Official portal for GSEB Class 10th results.',
  },
  {
    name: 'Gujarat Board HSC Class 12 Results',
    board: 'State',
    state: 'Gujarat',
    level: '12',
    examName: 'Gujarat Secondary and Higher Secondary Education Board - HSC',
    url: 'https://www.gseb.org',
    description: 'Official portal for GSEB Class 12th results.',
  },
  {
    name: 'Tamil Nadu SSLC Class 10 Results',
    board: 'State',
    state: 'Tamil Nadu',
    level: '10',
    examName: 'Directorate of Government Examinations Tamil Nadu - SSLC',
    url: 'https://tnresults.nic.in',
    description: 'Official portal for TN Class 10th results.',
  },
  {
    name: 'Tamil Nadu HSE Class 12 Results',
    board: 'State',
    state: 'Tamil Nadu',
    level: '12',
    examName: 'Directorate of Government Examinations Tamil Nadu - HSE',
    url: 'https://tnresults.nic.in',
    description: 'Official portal for TN Class 12th results.',
  },
  {
    name: 'Kerala SSLC Class 10 Results',
    board: 'State',
    state: 'Kerala',
    level: '10',
    examName: 'General Education Department Kerala - SSLC',
    url: 'https://results.kite.kerala.gov.in',
    description: 'Official portal for Kerala Class 10th results.',
  },
  {
    name: 'Kerala DHSE Class 12 Results',
    board: 'State',
    state: 'Kerala',
    level: '12',
    examName: 'Directorate of Higher Secondary Education Kerala - HSE',
    url: 'https://results.kite.kerala.gov.in',
    description: 'Official portal for Kerala Class 12th results.',
  },
  {
    name: 'Karnataka SSLC Class 10 Results',
    board: 'State',
    state: 'Karnataka',
    level: '10',
    examName: 'Karnataka School Examination and Assessment Board - SSLC',
    url: 'https://karresults.nic.in',
    description: 'Official portal for Karnataka Class 10th results.',
  },
  {
    name: 'Karnataka 2nd PUC Class 12 Results',
    board: 'State',
    state: 'Karnataka',
    level: '12',
    examName: 'Department of Pre-University Education Karnataka - 2nd PUC',
    url: 'https://karresults.nic.in',
    description: 'Official portal for Karnataka Class 12th results.',
  },
  {
    name: 'West Bengal Madhyamik Class 10 Results',
    board: 'State',
    state: 'West Bengal',
    level: '10',
    examName: 'West Bengal Board of Secondary Education - Madhyamik',
    url: 'https://wbresults.nic.in',
    description: 'Official portal for West Bengal Class 10th results.',
  },
  {
    name: 'West Bengal Uchcha Madhyamik Class 12 Results',
    board: 'State',
    state: 'West Bengal',
    level: '12',
    examName: 'West Bengal Council of Higher Secondary Education - Higher Secondary',
    url: 'https://wbresults.nic.in',
    description: 'Official portal for West Bengal Class 12th results.',
  },
  {
    name: 'Odisha Matric Class 10 Results',
    board: 'State',
    state: 'Odisha',
    level: '10',
    examName: 'Board of Secondary Education Odisha - HSC',
    url: 'https://orissaresults.nic.in',
    description: 'Official portal for Odisha Class 10th results.',
  },
  {
    name: 'Odisha CHSE Class 12 Results',
    board: 'State',
    state: 'Odisha',
    level: '12',
    examName: 'Council of Higher Secondary Education Odisha - Plus Two',
    url: 'https://orissaresults.nic.in',
    description: 'Official portal for Odisha Class 12th results.',
  },
  {
    name: 'Assam HSLC Class 10 Results',
    board: 'State',
    state: 'Assam',
    level: '10',
    examName: 'Board of Secondary Education Assam - HSLC',
    url: 'https://resultsassam.nic.in',
    description: 'Official portal for Assam Class 10th results.',
  },
  {
    name: 'Assam HS Class 12 Results',
    board: 'State',
    state: 'Assam',
    level: '12',
    examName: 'Assam Higher Secondary Education Council - Higher Secondary',
    url: 'https://resultsassam.nic.in',
    description: 'Official portal for Assam Class 12th results.',
  },
  {
    name: 'Telangana SSC Class 10 Results',
    board: 'State',
    state: 'Telangana',
    level: '10',
    examName: 'Board of Secondary Education Telangana - SSC',
    url: 'https://results.bsetelangana.org',
    description: 'Official portal for Telangana Class 10th results.',
  },
  {
    name: 'Telangana Intermediate Class 12 Results',
    board: 'State',
    state: 'Telangana',
    level: '12',
    examName: 'Telangana Board of Intermediate Education - HSE',
    url: 'https://results.bsetelangana.org',
    description: 'Official portal for Telangana Class 12th results.',
  },
  {
    name: 'Andhra Pradesh SSC Class 10 Results',
    board: 'State',
    state: 'Andhra Pradesh',
    level: '10',
    examName: 'Board of Secondary Education Andhra Pradesh - SSC',
    url: 'https://resultsbie.ap.gov.in',
    description: 'Official portal for Andhra Pradesh Class 10th results.',
  },
  {
    name: 'Andhra Pradesh Intermediate Class 12 Results',
    board: 'State',
    state: 'Andhra Pradesh',
    level: '12',
    examName: 'Board of Intermediate Education Andhra Pradesh - Intermediate',
    url: 'https://resultsbie.ap.gov.in',
    description: 'Official portal for Andhra Pradesh Class 12th results.',
  },
  {
    name: 'Chhattisgarh Class 10 Results',
    board: 'State',
    state: 'Chhattisgarh',
    level: '10',
    examName: 'Chhattisgarh Board of Secondary Education - High School',
    url: 'https://results.cg.nic.in',
    description: 'Official portal for Chhattisgarh Class 10th results.',
  },
  {
    name: 'Chhattisgarh Class 12 Results',
    board: 'State',
    state: 'Chhattisgarh',
    level: '12',
    examName: 'Chhattisgarh Board of Secondary Education - Higher Secondary',
    url: 'https://results.cg.nic.in',
    description: 'Official portal for Chhattisgarh Class 12th results.',
  },
  {
    name: 'Himachal Pradesh Class 10 Results',
    board: 'State',
    state: 'Himachal Pradesh',
    level: '10',
    examName: 'Himachal Pradesh Board of School Education - Matric',
    url: 'https://hpbose.org/Result.aspx',
    description: 'Official portal for Himachal Pradesh Class 10th results.',
  },
  {
    name: 'Himachal Pradesh Class 12 Results',
    board: 'State',
    state: 'Himachal Pradesh',
    level: '12',
    examName: 'Himachal Pradesh Board of School Education - Plus Two',
    url: 'https://hpbose.org/Result.aspx',
    description: 'Official portal for Himachal Pradesh Class 12th results.',
  },
  {
    name: 'Uttarakhand Class 10 Results',
    board: 'State',
    state: 'Uttarakhand',
    level: '10',
    examName: 'Uttarakhand Board of School Education - High School',
    url: 'https://uaresults.nic.in',
    description: 'Official portal for Uttarakhand Class 10th results.',
  },
  {
    name: 'Uttarakhand Class 12 Results',
    board: 'State',
    state: 'Uttarakhand',
    level: '12',
    examName: 'Uttarakhand Board of School Education - Intermediate',
    url: 'https://uaresults.nic.in',
    description: 'Official portal for Uttarakhand Class 12th results.',
  },
  {
    name: 'Goa SSC Class 10 Results',
    board: 'State',
    state: 'Goa',
    level: '10',
    examName: 'Goa Board of Secondary & Higher Secondary Education - SSC',
    url: 'https://gbshse.in',
    description: 'Official portal for Goa Class 10th results.',
  },
  {
    name: 'Goa HSSC Class 12 Results',
    board: 'State',
    state: 'Goa',
    level: '12',
    examName: 'Goa Board of Secondary & Higher Secondary Education - HSSC',
    url: 'https://gbshse.in',
    description: 'Official portal for Goa Class 12th results.',
  },
  {
    name: 'Meghalaya Class 10 Results',
    board: 'State',
    state: 'Meghalaya',
    level: '10',
    examName: 'Meghalaya Board of School Education - SSLC',
    url: 'http://megresults.nic.in',
    description: 'Official portal for Meghalaya Class 10th results.',
  },
  {
    name: 'Meghalaya Class 12 Results',
    board: 'State',
    state: 'Meghalaya',
    level: '12',
    examName: 'Meghalaya Board of School Education - HSSLC',
    url: 'http://megresults.nic.in',
    description: 'Official portal for Meghalaya Class 12th results.',
  },
  {
    name: 'Tripura Class 10 Results',
    board: 'State',
    state: 'Tripura',
    level: '10',
    examName: 'Tripura Board of Secondary Education - Madhyamik',
    url: 'https://tripuraresults.nic.in',
    description: 'Official portal for Tripura Class 10th results.',
  },
  {
    name: 'Tripura Class 12 Results',
    board: 'State',
    state: 'Tripura',
    level: '12',
    examName: 'Tripura Board of Secondary Education - Higher Secondary',
    url: 'https://tripuraresults.nic.in',
    description: 'Official portal for Tripura Class 12th results.',
  },
  {
    name: 'Jammu & Kashmir Class 10 Results',
    board: 'State',
    state: 'Jammu and Kashmir',
    level: '10',
    examName: 'Jammu & Kashmir Board of School Education - Secondary',
    url: 'https://jkbose.nic.in/results/',
    description: 'Official portal for J&K Class 10th results.',
  },
  {
    name: 'Jammu & Kashmir Class 12 Results',
    board: 'State',
    state: 'Jammu and Kashmir',
    level: '12',
    examName: 'Jammu & Kashmir Board of School Education - Higher Secondary',
    url: 'https://jkbose.nic.in/results/',
    description: 'Official portal for J&K Class 12th results.',
  }
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/vidyapath');
    console.log('Connected to MongoDB');

    // Remove existing active result sources to avoid duplicates
    await ResultSource.deleteMany({ status: 'active' });
    console.log('Cleared existing active ResultSources');

    const result = await ResultSource.insertMany(boardData);
    console.log(`Successfully seeded ${result.length} board result sources`);
  } catch (error) {
    console.error('Seeding error:', error);
  } finally {
    await mongoose.connection.close();
    console.log('MongoDB connection closed');
  }
}

seed();
