/**
 * 🌐 Source Registry — 200+ curated opportunity sources
 * Each source has metadata for smart crawling
 */

const SOURCES = [
  // ═══ CENTRAL GOVERNMENT SCHOLARSHIPS ═══
  { id: 'nsp', name: 'National Scholarship Portal', url: 'https://scholarships.gov.in/', strategy: 'puppeteer', priority: 'critical', scanInterval: 12, category: 'scholarship', region: 'national', enabled: true },
  { id: 'myscheme', name: 'MyScheme Portal', url: 'https://www.myscheme.gov.in/', strategy: 'puppeteer', priority: 'critical', scanInterval: 12, category: 'scheme', region: 'national', enabled: true },
  { id: 'inspire', name: 'INSPIRE Awards', url: 'https://www.inspireawards-dst.gov.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'national', enabled: true },
  { id: 'aim', name: 'Atal Innovation Mission', url: 'https://aim.gov.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'national', enabled: true },
  { id: 'dst', name: 'Dept of Science & Tech', url: 'https://www.dst.gov.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'scheme', region: 'national', enabled: true },
  { id: 'services-india', name: 'Services India Portal', url: 'https://services.india.gov.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'national', enabled: true },
  { id: 'data-gov', name: 'Open Data India', url: 'https://data.gov.in/', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'national', enabled: true },
  { id: 'pmcares', name: 'PM CARES Scholarship', url: 'https://pmcaresforchildren.in/scholarship', strategy: 'puppeteer', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'national', enabled: true },

  // ═══ STATE GOVERNMENT PORTALS ═══
  { id: 'mahadbt', name: 'MahaDBT Maharashtra', url: 'https://mahadbt.maharashtra.gov.in/', strategy: 'puppeteer', priority: 'critical', scanInterval: 12, category: 'scholarship', region: 'Maharashtra', enabled: true },
  { id: 'maha-edu', name: 'Maharashtra Education', url: 'https://education.maharashtra.gov.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'maha-exam', name: 'Maharashtra Exam Council', url: 'https://maa.ac.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'Maharashtra', enabled: true },
  { id: 'maha-sjsa', name: 'Maharashtra SJSA', url: 'https://sjsa.maharashtra.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'maha-minority', name: 'Maharashtra Minority Affairs', url: 'https://minorityaffairs.maharashtra.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'maha-tribal', name: 'Maharashtra Tribal', url: 'https://tribal.maharashtra.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'maha-women-child', name: 'Maharashtra Women & Child', url: 'https://womenchild.maharashtra.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'up-scholarship', name: 'UP Scholarship', url: 'https://scholarship.up.gov.in/', strategy: 'puppeteer', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'Uttar Pradesh', enabled: true },
  { id: 'up-samaj-kalyan', name: 'UP Samaj Kalyan', url: 'https://www.samajkalyanup.in', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'karnataka-ssp', name: 'Karnataka SSP', url: 'https://ssp.karnataka.gov.in/', strategy: 'puppeteer', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'Karnataka', enabled: true },
  { id: 'karnataka-dyes', name: 'Karnataka DYES', url: 'https://dyes.karnataka.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Karnataka', enabled: true },
  { id: 'karnataka-wcd', name: 'Karnataka WCD', url: 'https://wcd.karnataka.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Karnataka', enabled: true },
  { id: 'karnataka-culture', name: 'Karnataka Culture', url: 'https://kannadaculture.karnataka.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'competition', region: 'Karnataka', enabled: true },
  { id: 'telangana-epass', name: 'Telangana ePass', url: 'https://telanganaepass.cgg.gov.in/', strategy: 'puppeteer', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'Telangana', enabled: true },
  { id: 'telangana-school', name: 'Telangana School Edu', url: 'https://schooledu.telangana.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Telangana', enabled: true },
  { id: 'ap-jnanabhumi', name: 'AP Jnanabhumi', url: 'https://jnanabhumi.ap.gov.in/', strategy: 'puppeteer', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'Andhra Pradesh', enabled: true },
  { id: 'bihar-pms', name: 'Bihar PMS Online', url: 'https://pmsonline.bihar.gov.in/', strategy: 'puppeteer', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'Bihar', enabled: true },
  { id: 'bihar-medha', name: 'Bihar Medhasoft', url: 'https://medhasoft.bihar.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Bihar', enabled: true },
  { id: 'bihar-bbose', name: 'Bihar BBOSE', url: 'https://bboseonline.bihar.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Bihar', enabled: true },
  { id: 'bihar-ekalyan', name: 'Bihar eKalyan', url: 'https://ekalyan.bihar.gov.in', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Bihar', enabled: true },
  { id: 'bihar-inst-pms', name: 'Bihar Inst PMS', url: 'https://instpmsonline.bihar.gov.in', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Bihar', enabled: true },
  { id: 'bihar-education-dept', name: 'Bihar Education Dept', url: 'https://state.bihar.gov.in/educationbihar', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Bihar', enabled: true },
  { id: 'jharkhand-scholarship', name: 'Jharkhand Scholarship', url: 'https://scholarshipsdhte.jharkhand.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Jharkhand', enabled: true },
  { id: 'wb-banglar', name: 'West Bengal Banglar Shiksha', url: 'https://banglarshiksha.wb.gov.in/scholarships/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'West Bengal', enabled: true },
  { id: 'cg-scholarship', name: 'Chhattisgarh Scholarship', url: 'https://schoolscholarship.cg.nic.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Chhattisgarh', enabled: true },
  { id: 'mp-scholarship', name: 'MP Scholarship Portal', url: 'https://scholarshipportal.mp.nic.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Madhya Pradesh', enabled: true },
  { id: 'mp-social-justice', name: 'MP Social Justice', url: 'https://socialjustice.mp.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'mp-minority', name: 'MP Minority Affairs', url: 'https://minorityaffairs.mp.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'mp-tribal', name: 'MP Tribal Dept', url: 'https://www.tribal.mp.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'odisha-scholarship', name: 'Odisha Scholarship', url: 'https://scholarship.odisha.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Odisha', enabled: true },
  { id: 'kerala-egrantz', name: 'Kerala eGrantz', url: 'https://egrantz.kerala.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Kerala', enabled: true },
  { id: 'gujarat-digital', name: 'Digital Gujarat', url: 'https://www.digitalgujarat.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Gujarat', enabled: true },
  { id: 'haryana-scholarship', name: 'Haryana Scholarship', url: 'https://harchhatravratti.highereduhry.ac.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Haryana', enabled: true },
  { id: 'punjab-scholarship', name: 'Punjab Scholarships', url: 'https://scholarships.punjab.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Punjab', enabled: true },
  { id: 'assam-bidyarthi', name: 'Assam Bidyarthi', url: 'https://bidyarthi.assam.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Assam', enabled: true },
  { id: 'rajasthan-shala', name: 'Rajasthan Shala Darpan', url: 'https://rajshaladarpan.nic.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'raj-sje', name: 'Rajasthan SJE', url: 'https://sje.rajasthan.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'raj-sso', name: 'Rajasthan SSO', url: 'https://sso.rajasthan.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'wb-oasis', name: 'WB OASIS', url: 'https://oasis.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'West Bengal', enabled: true },
  { id: 'hp-epass', name: 'HP ePass', url: 'https://hpepass.cgg.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Himachal Pradesh', enabled: true },
  { id: 'ts-ekalyan', name: 'Telangana eKalyan', url: 'https://ekalyan.cgg.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Telangana', enabled: true },
  { id: 'uk-minority', name: 'Uttarakhand Minority Welfare', url: 'https://minoritywelfare.uk.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Uttarakhand', enabled: true },
  { id: 'delhi-ews', name: 'Delhi EWS Admissions', url: 'https://ewsadmissions.delhi.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Delhi', enabled: true },
  { id: 'delhi-edistrict', name: 'Delhi eDistrict', url: 'https://edistrict.delhigovt.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Delhi', enabled: true },
  { id: 'delhi-dsel', name: 'DSEL Delhi', url: 'https://dsel.education.gov.in/en/delhi', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Delhi', enabled: true },
  { id: 'manipur-minority', name: 'Manipur Minority', url: 'https://manipurminority.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Manipur', enabled: true },
  { id: 'telangana-minorities', name: 'Telangana Minorities', url: 'https://khammam.telangana.gov.in/minorities-welfare/', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Telangana', enabled: true },

  // ═══ EDUCATION BOARDS & EXAM PORTALS ═══
  { id: 'cbse', name: 'CBSE Academic', url: 'https://cbseacademic.nic.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'national', enabled: true },
  { id: 'cbse-main', name: 'CBSE Main', url: 'https://www.cbse.gov.in', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'academic', region: 'national', enabled: true },
  { id: 'ncert', name: 'NCERT', url: 'https://ncert.nic.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'academic', region: 'national', enabled: true },
  { id: 'cisce', name: 'CISCE', url: 'https://cisce.org', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'academic', region: 'national', enabled: true },
  { id: 'nios', name: 'NIOS', url: 'https://nios.ac.in', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'academic', region: 'national', enabled: true },
  { id: 'navodaya', name: 'Navodaya Vidyalaya', url: 'https://navodaya.gov.in', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'academic', region: 'national', enabled: true },
  { id: 'kvs', name: 'KVS Sangathan', url: 'https://kvsangathan.nic.in', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'academic', region: 'national', enabled: true },
  { id: 'dsel', name: 'Dept of School Education', url: 'https://dsel.education.gov.in', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'academic', region: 'national', enabled: true },
  { id: 'edudel', name: 'Delhi Education Dept', url: 'https://www.edudel.nic.in', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'academic', region: 'Delhi', enabled: true },
  { id: 'up-basic-edu', name: 'UP Basic Education', url: 'https://basiceducation.up.gov.in', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'academic', region: 'Uttar Pradesh', enabled: true },
  { id: 'raj-edu-board', name: 'Rajasthan Edu Board', url: 'https://rajeduboard.rajasthan.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Rajasthan', enabled: true },
  { id: 'raj-education', name: 'Rajasthan Education', url: 'https://education.rajasthan.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Rajasthan', enabled: true },
  { id: 'mp-education', name: 'MP Education Portal', url: 'https://educationportal.mp.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Madhya Pradesh', enabled: true },
  { id: 'mp-board', name: 'MP Board', url: 'https://mpbse.nic.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Madhya Pradesh', enabled: true },
  { id: 'mp-sos', name: 'MP Open School', url: 'https://mpsos.nic.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Madhya Pradesh', enabled: true },
  { id: 'up-board', name: 'UP Board (UPMSP)', url: 'https://upmsp.edu.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Uttar Pradesh', enabled: true },
  { id: 'bihar-board', name: 'Bihar Board', url: 'https://biharboardonline.bihar.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Bihar', enabled: true },
  { id: 'bihar-scert', name: 'Bihar SCERT', url: 'https://scert.bihar.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Bihar', enabled: true },
  { id: 'delhi-scert', name: 'Delhi SCERT', url: 'https://scert.delhi.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Delhi', enabled: true },
  { id: 'mp-scert', name: 'MP SCERT', url: 'https://scert.mp.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Madhya Pradesh', enabled: true },
  { id: 'raj-scert', name: 'Rajasthan SCERT', url: 'https://scert.rajasthan.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Rajasthan', enabled: true },
  { id: 'haryana-scert', name: 'Haryana SCERT', url: 'https://scertharyana.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Haryana', enabled: true },
  { id: 'karnataka-education', name: 'Karnataka Education', url: 'https://schooleducation.karnataka.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Karnataka', enabled: true },
  { id: 'karnataka-board', name: 'Karnataka Board (KSEEB)', url: 'https://kseeb.karnataka.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Karnataka', enabled: true },
  { id: 'telangana-school-edu', name: 'Telangana School Edu', url: 'https://schooledu.telangana.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Telangana', enabled: true },
  { id: 'maharashtra-board', name: 'Maharashtra Board', url: 'https://www.mahahsscboard.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Maharashtra', enabled: true },
  { id: 'msce', name: 'Maharashtra MSCE', url: 'https://www.msce.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Maharashtra', enabled: true },
  { id: 'raj-rsos', name: 'Rajasthan Open School', url: 'https://rsos.rajasthan.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'academic', region: 'Rajasthan', enabled: true },
  { id: 'cobse', name: 'COBSE', url: 'https://www.cobse.org.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'academic', region: 'national', enabled: true },
  { id: 'dsbose', name: 'DSBOSE', url: 'https://www.dsbose.com', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'academic', region: 'national', enabled: true },
  { id: 'parakh', name: 'PARAKH NCERT', url: 'https://parakh.ncert.gov.in/list-of-boards', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'academic', region: 'national', enabled: true },

  // ═══ OLYMPIAD & COMPETITION ORGANIZATIONS ═══
  { id: 'hbcse', name: 'HBCSE Olympiad', url: 'https://www.hbcse.tifr.res.in/olympiad', strategy: 'cheerio', priority: 'critical', scanInterval: 12, category: 'olympiad', region: 'national', enabled: true },
  { id: 'sof', name: 'SOF Olympiads', url: 'https://www.sofworld.org/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'olympiad', region: 'national', enabled: true },
  { id: 'unified-council', name: 'Unified Council', url: 'https://www.unifiedcouncil.com/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'olympiad', region: 'national', enabled: true },
  { id: 'crest-olympiads', name: 'CREST Olympiads', url: 'https://www.crestolympiads.com/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'olympiad', region: 'international', enabled: true },
  { id: 'imo-official', name: 'IMO Official', url: 'https://www.imo-official.org/', strategy: 'cheerio', priority: 'high', scanInterval: 48, category: 'olympiad', region: 'international', enabled: true },
  { id: 'iapt', name: 'IAPT Physics', url: 'https://www.iapt.org.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'olympiad', region: 'national', enabled: true },
  { id: 'ipho', name: 'IPhO', url: 'https://ipho.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'international', enabled: true },
  { id: 'icho', name: 'IChO', url: 'https://icho.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'international', enabled: true },
  { id: 'ioi', name: 'IOI', url: 'https://ioinformatics.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'international', enabled: true },
  { id: 'ioaa', name: 'IOAA', url: 'https://www.ioaastrophysics.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'international', enabled: true },
  { id: 'ibo', name: 'IBO', url: 'https://www.ibo-info.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'international', enabled: true },
  { id: 'ijso', name: 'IJSO Delegation', url: 'https://www.ijsodelegation.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'international', enabled: true },
  { id: 'kangaroo', name: 'Math Kangaroo India', url: 'http://www.kangaroo.org.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'olympiad', region: 'international', enabled: true },
  { id: 'ikmc', name: 'IKMC Kangaroo', url: 'https://ikmc.kangaroo.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'international', enabled: true },
  { id: 'immc', name: 'IMMC Challenge', url: 'https://www.immchallenge.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'international', enabled: true },
  { id: 'brain-bee', name: 'Brain Bee', url: 'https://www.internationalbrainbee.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'international', enabled: true },
  { id: 'egmo', name: 'EGMO', url: 'https://www.egmo.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'international', enabled: true },
  { id: 'ei-india', name: 'EI India', url: 'https://www.ei-india.com/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'national', enabled: true },

  // ═══ INNOVATION, STEM & ISRO ═══
  { id: 'sih', name: 'Smart India Hackathon', url: 'https://www.sih.gov.in', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'national', enabled: true },
  { id: 'mygov', name: 'MyGov India', url: 'https://www.mygov.in', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'national', enabled: true },
  { id: 'vigyan-prasar', name: 'Vigyan Prasar', url: 'https://vigyanprasar.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'national', enabled: true },
  { id: 'isro-students', name: 'ISRO Student Programs', url: 'https://www.isro.gov.in/Students.html', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'national', enabled: true },
  { id: 'isro-spacetutor', name: 'ISRO Space Tutor', url: 'https://www.isro.gov.in/spacetutor.html', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'national', enabled: true },
  { id: 'imaven', name: 'IMaven Space Tutor', url: 'https://imaven.org/about/isro-registered-space-tutor/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'national', enabled: true },
  { id: 'atl-india', name: 'ATL India', url: 'https://atlindia.in', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'national', enabled: true },
  { id: 'ncert-science-exhibition', name: 'NCERT Science Exhibition', url: 'https://ncert.nic.in/jn-national-science-exhibition.php', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'national', enabled: true },
  { id: 'ncert-kala-utsav', name: 'NCERT Kala Utsav', url: 'https://ncert.nic.in/kala-utsav.php', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'national', enabled: true },
  { id: 'ncert-ntse', name: 'NCERT NTSE', url: 'https://ncert.nic.in/national-talent-examination.php', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'national', enabled: true },

  // ═══ ROBOTICS & STEM ═══
  { id: 'wro', name: 'World Robot Olympiad', url: 'https://www.wro-association.org/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'international', enabled: true },
  { id: 'fll', name: 'FIRST LEGO League', url: 'https://www.firstlegoleague.org/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'international', enabled: true },
  { id: 'nasa-stem', name: 'NASA STEM', url: 'https://www.nasa.gov/stem', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'international', enabled: true },
  { id: 'google-sciencefair', name: 'Google Science Fair', url: 'https://www.google.com/intl/en_iw/edu/sciencefair/', strategy: 'cheerio', priority: 'high', scanInterval: 48, category: 'competition', region: 'international', enabled: true },
  { id: 'society-science', name: 'Society for Science', url: 'https://www.societyforscience.org/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'international', enabled: true },
  { id: 'dso', name: 'DSO World', url: 'https://dso.world/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'international', enabled: true },

  // ═══ SPORTS (National & State Sports Departments) ═══
  { id: 'khelo-india', name: 'Khelo India', url: 'https://kheloindia.gov.in/', strategy: 'cheerio', priority: 'critical', scanInterval: 12, category: 'sports', region: 'national', enabled: true },
  { id: 'sai', name: 'Sports Authority of India', url: 'https://sportsauthorityofindia.nic.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'sports', region: 'national', enabled: true },
  { id: 'yas', name: 'Youth Affairs & Sports', url: 'https://yas.gov.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'sports', region: 'national', enabled: true },
  { id: 'sgfi', name: 'School Games Federation of India', url: 'https://sgfi.org.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'sports', region: 'national', enabled: true },
  { id: 'khelo-sfw', name: 'Khelo India SFW', url: 'https://sfw.kheloindia.gov.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 24, category: 'sports', region: 'national', enabled: true },
  { id: 'khelo-fitness', name: 'Khelo India Fitness', url: 'https://schoolfitness.kheloindia.gov.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'sports', region: 'national', enabled: true },
  { id: 'khelsathi', name: 'Khel Sathi', url: 'https://khelsathi.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'sports', region: 'national', enabled: true },
  { id: 'student-games', name: 'Student Games India', url: 'https://studentgames.ind.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'sports', region: 'national', enabled: true },
  { id: 'ncc', name: 'NCC India', url: 'https://nccindia.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'sports', region: 'national', enabled: true },
  { id: 'cbse-sports', name: 'CBSE Sports', url: 'https://cbseacademic.nic.in/sports.html', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'sports', region: 'national', enabled: true },
  { id: 'maharashtra-sports', name: 'Maharashtra Sports', url: 'https://mahasports.maharashtra.gov.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'sports', region: 'Maharashtra', enabled: true },
  { id: 'rajasthan-sports', name: 'Rajasthan Sports', url: 'https://sports.rajasthan.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'sports', region: 'Rajasthan', enabled: true },
  { id: 'bihar-sports', name: 'Bihar Sports Authority', url: 'https://sportsauthority.bihar.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'sports', region: 'Bihar', enabled: true },
  { id: 'bihar-sports-dept', name: 'Bihar Sports Dept', url: 'https://state.bihar.gov.in/sport/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'sports', region: 'Bihar', enabled: true },
  { id: 'meghalaya-sports', name: 'Meghalaya Sports', url: 'https://megsports.gov.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'sports', region: 'Meghalaya', enabled: true },
  { id: 'india-skate', name: 'India Skate', url: 'https://indiaskate.com/skaterbase26/', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'sports', region: 'national', enabled: true },
  { id: 'mp-sports', name: 'MP Sports Dept', url: 'https://dsywmp.gov.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'sports', region: 'Madhya Pradesh', enabled: true },
  { id: 'nyks', name: 'Nehru Yuva Kendra', url: 'https://nyks.nic.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'sports', region: 'national', enabled: true },

  // ═══ SCHOLARSHIP AGGREGATORS ═══
  { id: 'buddy4study', name: 'Buddy4Study Scholarships', url: 'https://www.buddy4study.com/scholarships', strategy: 'puppeteer', priority: 'critical', scanInterval: 12, category: 'scholarship', region: 'national', enabled: true },
  { id: 'vidyasaarathi', name: 'Vidyasaarathi', url: 'https://www.vidyasaarathi.co.in/', strategy: 'puppeteer', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'national', enabled: true },
  { id: 'unstop', name: 'Unstop Competitions', url: 'https://unstop.com/', strategy: 'puppeteer', priority: 'critical', scanInterval: 12, category: 'competition', region: 'national', enabled: true },
  { id: 'internshala', name: 'Internshala', url: 'https://internshala.com/', strategy: 'puppeteer', priority: 'high', scanInterval: 24, category: 'internship', region: 'national', enabled: true },
  { id: 'scholarsbox', name: 'ScholarsBox', url: 'https://scholarsbox.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 24, category: 'scholarship', region: 'national', enabled: true },
  { id: 'edumithra', name: 'EduMithra', url: 'https://edumithra.com/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'national', enabled: true },
  { id: 'scholarlify', name: 'Scholarlify', url: 'https://scholarlify.com/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'national', enabled: true },
  { id: 'global-scholarship', name: 'Global Scholarship', url: 'https://www.theglobalscholarship.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'international', enabled: true },

  // ═══ NEWS & EDUCATION PORTALS ═══
  { id: 'careers360', name: 'Careers360 Scholarships', url: 'https://www.careers360.com/scholarships', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'national', enabled: true },
  { id: 'shiksha', name: 'Shiksha Scholarships', url: 'https://www.shiksha.com/scholarships-in-india', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'national', enabled: true },
  { id: 'collegedekho', name: 'CollegeDekho Scholarships', url: 'https://www.collegedekho.com/scholarships/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'national', enabled: true },
  { id: 'jagranjosh', name: 'Jagran Josh Scholarships', url: 'https://www.jagranjosh.com/scholarships', strategy: 'cheerio', priority: 'medium', scanInterval: 24, category: 'scholarship', region: 'national', enabled: true },

  // ═══ CORPORATE SCHOLARSHIPS ═══
  { id: 'tcs', name: 'TCS', url: 'https://www.tcs.com/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'national', enabled: true },
  { id: 'infosys-foundation', name: 'Infosys Foundation', url: 'https://www.infosys.com/infosys-foundation.html', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'national', enabled: true },

  // ═══ UNIVERSITY PORTALS ═══
  { id: 'unipune', name: 'Pune University', url: 'https://www.unipune.ac.in/', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'academic', region: 'Maharashtra', enabled: true },
  { id: 'mu', name: 'Mumbai University', url: 'https://mu.ac.in/', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'academic', region: 'Maharashtra', enabled: true },

  // ═══ ADDITIONAL TARGET URLS (from targetUrls.js) ═══
  { id: 'mah-results', name: 'Maharashtra Results', url: 'https://mahresults.nic.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'Maharashtra', enabled: true },
  { id: 'cmo-official', name: 'Chinese Math Olympiad', url: 'https://www.cmo.org.cn/', strategy: 'cheerio', priority: 'medium', scanInterval: 72, category: 'olympiad', region: 'international', enabled: true },
  { id: 'ioqs', name: 'Intl Olympiad Quantum Science', url: 'https://www.ioqs.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 72, category: 'olympiad', region: 'international', enabled: true },
  { id: 'scholastic-world', name: 'Scholastic World', url: 'https://scholasticworld.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'national', enabled: true },
  { id: 'vi-learning', name: 'Vodafone Idea Learning', url: 'https://learningwithvodafoneidea.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'national', enabled: true },
  { id: 'ap-social-welfare', name: 'AP Social Welfare', url: 'https://socialwelfare.apcfss.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'Andhra Pradesh', enabled: true },
  { id: 'tn-mdm', name: 'TN Mid Day Meal', url: 'https://middaymeal.tn.gov.in/', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Tamil Nadu', enabled: true },
  { id: 'up-mdm', name: 'UP Mid Day Meal', url: 'https://upmdm.in/', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'national-mdm', name: 'National Mid Day Meal', url: 'https://mdm.nic.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 72, category: 'scheme', region: 'national', enabled: true },
  { id: 'mp-he-scholarship', name: 'MP Higher Education Scholarship', url: 'https://hescholarship.mp.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Madhya Pradesh', enabled: true },
  { id: 'bihar-medhasoft-nic', name: 'Bihar Medhasoft (NIC)', url: 'https://medhasoft.bih.nic.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Bihar', enabled: true },
  { id: 'bihar-pms-nic', name: 'Bihar PMS (NIC)', url: 'https://pmsonline.bih.nic.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Bihar', enabled: true },
  { id: 'wb-mdfc', name: 'WB MDFC Scholarship', url: 'https://wbmdfcscholarship.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'West Bengal', enabled: true },
  { id: 'rte-grievance', name: 'RTE Grievance Portal', url: 'https://righttoeducation.in/report-a-grievance', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'national', enabled: true },
  { id: 'bal-bhavan', name: 'National Bal Bhavan', url: 'https://nationalbalbhavan.nic.in', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'competition', region: 'national', enabled: true },
  { id: 'bal-bharati', name: 'Bal Bharati', url: 'https://balbharati.in', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'national', enabled: true },
  { id: 'msdetrg', name: 'MSDETRG', url: 'https://msdetrg.com', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'academic', region: 'Maharashtra', enabled: true },
  { id: 'pib-education', name: 'PIB Education', url: 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2247718', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'national', enabled: true },

  // ═══ DISTRICT PORTALS (local govt schemes & opportunities) ═══
  { id: 'dist-agarmalwa', name: 'Agarmalwa District', url: 'https://agarmalwa.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-agra', name: 'Agra District', url: 'https://agra.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-ahmednagar', name: 'Ahmednagar District', url: 'https://ahmednagar.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-ajmer', name: 'Ajmer District', url: 'https://ajmer.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-akola', name: 'Akola District', url: 'https://akola.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-aligarh', name: 'Aligarh District', url: 'https://aligarh.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-alirajpur', name: 'Alirajpur District', url: 'https://alirajpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-alwar', name: 'Alwar District', url: 'https://alwar.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-ambedkarnagar', name: 'Ambedkarnagar District', url: 'https://ambedkarnagar.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-amethi', name: 'Amethi District', url: 'https://amethi.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-amravati', name: 'Amravati District', url: 'https://amravati.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-amroha', name: 'Amroha District', url: 'https://amroha.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-anuppur', name: 'Anuppur District', url: 'https://anuppur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-ashoknagar', name: 'Ashoknagar District', url: 'https://ashoknagar.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-auraiya', name: 'Auraiya District', url: 'https://auraiya.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-aurangabad', name: 'Aurangabad District', url: 'https://aurangabad.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Bihar', enabled: true },
  { id: 'dist-ayodhya', name: 'Ayodhya District', url: 'https://ayodhya.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-azamgarh', name: 'Azamgarh District', url: 'https://azamgarh.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-bagalkot', name: 'Bagalkot District', url: 'https://bagalkot.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Karnataka', enabled: true },
  { id: 'dist-baghpat', name: 'Baghpat District', url: 'https://baghpat.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-bahraich', name: 'Bahraich District', url: 'https://bahraich.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-balaghat', name: 'Balaghat District', url: 'https://balaghat.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-ballia', name: 'Ballia District', url: 'https://ballia.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-balrampur', name: 'Balrampur District', url: 'https://balrampur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-banda', name: 'Banda District', url: 'https://banda.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-banswara', name: 'Banswara District', url: 'https://banswara.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-barabanki', name: 'Barabanki District', url: 'https://barabanki.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-baran', name: 'Baran District', url: 'https://baran.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-bareilly', name: 'Bareilly District', url: 'https://bareilly.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-barmer', name: 'Barmer District', url: 'https://barmer.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-barwani', name: 'Barwani District', url: 'https://barwani.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-basti', name: 'Basti District', url: 'https://basti.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-beed', name: 'Beed District', url: 'https://beed.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-bengaluruurban', name: 'Bengaluruurban District', url: 'https://bengaluruurban.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Karnataka', enabled: true },
  { id: 'dist-betul', name: 'Betul District', url: 'https://betul.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-bhadohi', name: 'Bhadohi District', url: 'https://bhadohi.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-bhandara', name: 'Bhandara District', url: 'https://bhandara.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-bharatpur', name: 'Bharatpur District', url: 'https://bharatpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-bhilwara', name: 'Bhilwara District', url: 'https://bhilwara.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-bhind', name: 'Bhind District', url: 'https://bhind.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-bhopal', name: 'Bhopal District', url: 'https://bhopal.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-bikaner', name: 'Bikaner District', url: 'https://bikaner.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-buldhana', name: 'Buldhana District', url: 'https://buldhana.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-bundi', name: 'Bundi District', url: 'https://bundi.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-burhanpur', name: 'Burhanpur District', url: 'https://burhanpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-chandrapur', name: 'Chandrapur District', url: 'https://chandrapur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-chhatarpur', name: 'Chhatarpur District', url: 'https://chhatarpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-chhindwara', name: 'Chhindwara District', url: 'https://chhindwara.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-chitrakoot', name: 'Chitrakoot District', url: 'https://chitrakoot.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-chittorgarh', name: 'Chittorgarh District', url: 'https://chittorgarh.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-churu', name: 'Churu District', url: 'https://churu.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-damoh', name: 'Damoh District', url: 'https://damoh.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-datia', name: 'Datia District', url: 'https://datia.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-dausa', name: 'Dausa District', url: 'https://dausa.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-deoria', name: 'Deoria District', url: 'https://deoria.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-dewas', name: 'Dewas District', url: 'https://dewas.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-dhar', name: 'Dhar District', url: 'https://dhar.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-dholpur', name: 'Dholpur District', url: 'https://dholpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-dhule', name: 'Dhule District', url: 'https://dhule.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-dindori', name: 'Dindori District', url: 'https://dindori.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-dungarpur', name: 'Dungarpur District', url: 'https://dungarpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-etah', name: 'Etah District', url: 'https://etah.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-etawah', name: 'Etawah District', url: 'https://etawah.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-farrukhabad', name: 'Farrukhabad District', url: 'https://farrukhabad.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-fatehpur', name: 'Fatehpur District', url: 'https://fatehpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-firozabad', name: 'Firozabad District', url: 'https://firozabad.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-gadchiroli', name: 'Gadchiroli District', url: 'https://gadchiroli.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-gbnagar', name: 'Gbnagar District', url: 'https://gbnagar.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-ghaziabad', name: 'Ghaziabad District', url: 'https://ghaziabad.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-ghazipur', name: 'Ghazipur District', url: 'https://ghazipur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-gonda', name: 'Gonda District', url: 'https://gonda.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-gondia', name: 'Gondia District', url: 'https://gondia.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-gorakhpur', name: 'Gorakhpur District', url: 'https://gorakhpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-guna', name: 'Guna District', url: 'https://guna.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-gwalior', name: 'Gwalior District', url: 'https://gwalior.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-hamirpur', name: 'Hamirpur District', url: 'https://hamirpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-hanumangarh', name: 'Hanumangarh District', url: 'https://hanumangarh.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Rajasthan', enabled: true },
  { id: 'dist-hapur', name: 'Hapur District', url: 'https://hapur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-harda', name: 'Harda District', url: 'https://harda.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-hardoi', name: 'Hardoi District', url: 'https://hardoi.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-hathras', name: 'Hathras District', url: 'https://hathras.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-hingoli', name: 'Hingoli District', url: 'https://hingoli.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-indore', name: 'Indore District', url: 'https://indore.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-jabalpur', name: 'Jabalpur District', url: 'https://jabalpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-jalaun', name: 'Jalaun District', url: 'https://jalaun.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-jalgaon', name: 'Jalgaon District', url: 'https://jalgaon.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-jalna', name: 'Jalna District', url: 'https://jalna.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-jaunpur', name: 'Jaunpur District', url: 'https://jaunpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-jhabua', name: 'Jhabua District', url: 'https://jhabua.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-jhansi', name: 'Jhansi District', url: 'https://jhansi.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-kannauj', name: 'Kannauj District', url: 'https://kannauj.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-kanpurdehat', name: 'Kanpurdehat District', url: 'https://kanpurdehat.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-kanpurnagar', name: 'Kanpurnagar District', url: 'https://kanpurnagar.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-kasganj', name: 'Kasganj District', url: 'https://kasganj.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-katni', name: 'Katni District', url: 'https://katni.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-kaushambi', name: 'Kaushambi District', url: 'https://kaushambi.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-khandwa', name: 'Khandwa District', url: 'https://khandwa.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-khargone', name: 'Khargone District', url: 'https://khargone.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-kheri', name: 'Kheri District', url: 'https://kheri.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-kolhapur', name: 'Kolhapur District', url: 'https://kolhapur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-kushinagar', name: 'Kushinagar District', url: 'https://kushinagar.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-lalitpur', name: 'Lalitpur District', url: 'https://lalitpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-latur', name: 'Latur District', url: 'https://latur.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-lucknow', name: 'Lucknow District', url: 'https://lucknow.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-maharajganj', name: 'Maharajganj District', url: 'https://maharajganj.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-mahoba', name: 'Mahoba District', url: 'https://mahoba.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-mainpuri', name: 'Mainpuri District', url: 'https://mainpuri.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-mandla', name: 'Mandla District', url: 'https://mandla.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-mandsaur', name: 'Mandsaur District', url: 'https://mandsaur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-mathura', name: 'Mathura District', url: 'https://mathura.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-mau', name: 'Mau District', url: 'https://mau.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-mauganj', name: 'Mauganj District', url: 'https://mauganj.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-meerut', name: 'Meerut District', url: 'https://meerut.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-mirzapur', name: 'Mirzapur District', url: 'https://mirzapur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-moradabad', name: 'Moradabad District', url: 'https://moradabad.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-morena', name: 'Morena District', url: 'https://morena.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-muzaffarnagar', name: 'Muzaffarnagar District', url: 'https://muzaffarnagar.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-nagpur', name: 'Nagpur District', url: 'https://nagpur.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-nanded', name: 'Nanded District', url: 'https://nanded.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-nandurbar', name: 'Nandurbar District', url: 'https://nandurbar.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-narmadapuram', name: 'Narmadapuram District', url: 'https://narmadapuram.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-narsinghpur', name: 'Narsinghpur District', url: 'https://narsinghpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-nashik', name: 'Nashik District', url: 'https://nashik.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-neemuch', name: 'Neemuch District', url: 'https://neemuch.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-niwari', name: 'Niwari District', url: 'https://niwari.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-osmanabad', name: 'Osmanabad District', url: 'https://osmanabad.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-palghar', name: 'Palghar District', url: 'https://palghar.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-pandhurna', name: 'Pandhurna District', url: 'https://pandhurna.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-panna', name: 'Panna District', url: 'https://panna.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-pilibhit', name: 'Pilibhit District', url: 'https://pilibhit.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-pratapgarh', name: 'Pratapgarh District', url: 'https://pratapgarh.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-prayagraj', name: 'Prayagraj District', url: 'https://prayagraj.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-pune', name: 'Pune District', url: 'https://pune.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-raebareli', name: 'Raebareli District', url: 'https://raebareli.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-raigad', name: 'Raigad District', url: 'https://raigad.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-raisen', name: 'Raisen District', url: 'https://raisen.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-rajgarh', name: 'Rajgarh District', url: 'https://rajgarh.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-rampur', name: 'Rampur District', url: 'https://rampur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-ratlam', name: 'Ratlam District', url: 'https://ratlam.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-ratnagiri', name: 'Ratnagiri District', url: 'https://ratnagiri.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-rewa', name: 'Rewa District', url: 'https://rewa.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-sagar', name: 'Sagar District', url: 'https://sagar.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-saharanpur', name: 'Saharanpur District', url: 'https://saharanpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-sambhal', name: 'Sambhal District', url: 'https://sambhal.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-sangli', name: 'Sangli District', url: 'https://sangli.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-santkabirnagar', name: 'Santkabirnagar District', url: 'https://santkabirnagar.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-satara', name: 'Satara District', url: 'https://satara.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-satna', name: 'Satna District', url: 'https://satna.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-sehore', name: 'Sehore District', url: 'https://sehore.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-seoni', name: 'Seoni District', url: 'https://seoni.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-shahdol', name: 'Shahdol District', url: 'https://shahdol.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-shahjahanpur', name: 'Shahjahanpur District', url: 'https://shahjahanpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-shajapur', name: 'Shajapur District', url: 'https://shajapur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-shamli', name: 'Shamli District', url: 'https://shamli.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-sheopur', name: 'Sheopur District', url: 'https://sheopur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-shivpuri', name: 'Shivpuri District', url: 'https://shivpuri.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-shravasti', name: 'Shravasti District', url: 'https://shravasti.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-siddharthnagar', name: 'Siddharthnagar District', url: 'https://siddharthnagar.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-sidhi', name: 'Sidhi District', url: 'https://sidhi.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-sindhudurg', name: 'Sindhudurg District', url: 'https://sindhudurg.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-singrauli', name: 'Singrauli District', url: 'https://singrauli.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-sitapur', name: 'Sitapur District', url: 'https://sitapur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-solapur', name: 'Solapur District', url: 'https://solapur.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-sonbhadra', name: 'Sonbhadra District', url: 'https://sonbhadra.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-sultanpur', name: 'Sultanpur District', url: 'https://sultanpur.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-thane', name: 'Thane District', url: 'https://thane.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-tikamgarh', name: 'Tikamgarh District', url: 'https://tikamgarh.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-ujjain', name: 'Ujjain District', url: 'https://ujjain.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-umaria', name: 'Umaria District', url: 'https://umaria.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-unnao', name: 'Unnao District', url: 'https://unnao.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-varanasi', name: 'Varanasi District', url: 'https://varanasi.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Uttar Pradesh', enabled: true },
  { id: 'dist-vidisha', name: 'Vidisha District', url: 'https://vidisha.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Madhya Pradesh', enabled: true },
  { id: 'dist-wardha', name: 'Wardha District', url: 'https://wardha.nic.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-washim', name: 'Washim District', url: 'https://washim.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },
  { id: 'dist-yavatmal', name: 'Yavatmal District', url: 'https://yavatmal.gov.in', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scheme', region: 'Maharashtra', enabled: true },

  // ═══ 🔥 NEW: Major Scholarship Aggregators & Portals ═══
  { id: 'aicte', name: 'AICTE India', url: 'https://www.aicte-india.org/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'national', enabled: true },
  { id: 'ugc', name: 'UGC India', url: 'https://www.ugc.gov.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'national', enabled: true },
  { id: 'inspire-dst', name: 'DST INSPIRE Online', url: 'https://online-inspire.gov.in/', strategy: 'puppeteer', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'national', enabled: true },
  { id: 'reliance-foundation', name: 'Reliance Foundation Scholarships', url: 'https://scholarships.reliancefoundation.org/', strategy: 'cheerio', priority: 'high', scanInterval: 48, category: 'scholarship', region: 'national', enabled: true },
  { id: 'hdfc-scholarship', name: 'HDFC Bank Scholarship', url: 'https://www.hdfcbank.com/personal/save/scholarship-programme', strategy: 'cheerio', priority: 'medium', scanInterval: 72, category: 'scholarship', region: 'national', enabled: true },
  { id: 'vidyasaarathi', name: 'Vidyasaarathi', url: 'https://www.vidyasaarathi.co.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'national', enabled: true },
  { id: 'medhavi', name: 'Medhavi Online', url: 'https://www.medhavionline.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'national', enabled: true },
  { id: 'vidyadhan', name: 'Vidyadhan Scholarship', url: 'https://www.vidyadhan.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'national', enabled: true },
  { id: 'fairgaze', name: 'FairGaze Scholarships', url: 'https://www.fairgaze.com/scholarships.html', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scholarship', region: 'national', enabled: true },
  { id: 'nta', name: 'NTA Exams & Scholarships', url: 'https://nta.ac.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'scholarship', region: 'national', enabled: true },
  { id: 'diksha', name: 'DIKSHA Portal', url: 'https://diksha.gov.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'scheme', region: 'national', enabled: true },

  // ═══ State Scholarship Portals (Additional) ═══
  { id: 'punjab-scholarship', name: 'Punjab Scholarship', url: 'https://scholarships.punjab.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Punjab', enabled: true },
  { id: 'gujarat-scholarship', name: 'Gujarat Scholarship', url: 'https://www.digitalgujarat.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Gujarat', enabled: true },
  { id: 'odisha-scholarship', name: 'Odisha Scholarship', url: 'https://scholarship.odisha.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Odisha', enabled: true },
  { id: 'rajasthan-scholarship', name: 'Rajasthan Scholarship', url: 'https://hte.rajasthan.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Rajasthan', enabled: true },
  { id: 'west-bengal-scholarship', name: 'West Bengal Scholarship', url: 'https://svmcm.wb.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'West Bengal', enabled: true },
  { id: 'kerala-scholarship', name: 'Kerala Scholarship', url: 'https://www.dcescholarship.kerala.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Kerala', enabled: true },
  { id: 'tamilnadu-scholarship', name: 'Tamil Nadu Scholarship', url: 'https://escholarship.tn.gov.in/', strategy: 'puppeteer', priority: 'medium', scanInterval: 48, category: 'scholarship', region: 'Tamil Nadu', enabled: true },
  { id: 'assam-scholarship', name: 'Assam Scholarship', url: 'https://directorateschooledu.assam.gov.in/', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scholarship', region: 'Assam', enabled: true },

  // ═══ International Scholarships ═══
  { id: 'fulbright', name: 'Fulbright-Nehru Fellowship (USIEF)', url: 'https://www.usief.org.in/', strategy: 'cheerio', priority: 'high', scanInterval: 48, category: 'scholarship', region: 'international', enabled: true },
  { id: 'chevening', name: 'Chevening Scholarship', url: 'https://www.chevening.org/scholarships/', strategy: 'cheerio', priority: 'medium', scanInterval: 72, category: 'scholarship', region: 'international', enabled: true },
  { id: 'daad', name: 'DAAD Germany Scholarships', url: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/', strategy: 'cheerio', priority: 'medium', scanInterval: 72, category: 'scholarship', region: 'international', enabled: true },
  { id: 'erasmus', name: 'Erasmus Plus', url: 'https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals', strategy: 'cheerio', priority: 'medium', scanInterval: 72, category: 'scholarship', region: 'international', enabled: true },
  { id: 'commonwealth', name: 'Commonwealth Scholarships', url: 'https://cscuk.fcdo.gov.uk/scholarships/', strategy: 'cheerio', priority: 'medium', scanInterval: 72, category: 'scholarship', region: 'international', enabled: true },
  { id: 'mext', name: 'MEXT Japan Scholarship', url: 'https://www.studyinjapan.go.jp/en/smap-stopj-applications-scholarship.html', strategy: 'cheerio', priority: 'medium', scanInterval: 72, category: 'scholarship', region: 'international', enabled: true },

  // ═══ Competitions & Hackathons ═══
  { id: 'sih', name: 'Smart India Hackathon', url: 'https://www.sih.gov.in/', strategy: 'puppeteer', priority: 'critical', scanInterval: 24, category: 'competition', region: 'national', enabled: true },
  { id: 'codechef', name: 'CodeChef', url: 'https://www.codechef.com/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'national', enabled: true },
  { id: 'hackerrank', name: 'HackerRank Compete', url: 'https://www.hackerrank.com/contests', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'international', enabled: true },
  { id: 'leetcode', name: 'LeetCode Contests', url: 'https://leetcode.com/contest/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'international', enabled: true },
  { id: 'unstop', name: 'Unstop Competitions', url: 'https://unstop.com/competitions', strategy: 'cheerio', priority: 'critical', scanInterval: 12, category: 'competition', region: 'national', enabled: true },
  { id: 'kaggle', name: 'Kaggle Competitions', url: 'https://www.kaggle.com/competitions', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'international', enabled: true },
  { id: 'devfolio', name: 'Devfolio Hackathons', url: 'https://devfolio.co/hackathons', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'competition', region: 'international', enabled: true },
  { id: 'devpost', name: 'Devpost Challenges', url: 'https://devpost.com/hackathons', strategy: 'cheerio', priority: 'medium', scanInterval: 72, category: 'competition', region: 'international', enabled: true },
  { id: 'mlh', name: 'Major League Hacking', url: 'https://mlh.io/seasons/2026/events', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'competition', region: 'international', enabled: true },

  // ═══ Olympiads ═══
  { id: 'hbcse', name: 'HBCSE Olympiads', url: 'https://olympiads.hbcse.tifr.res.in/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'olympiad', region: 'national', enabled: true },
  { id: 'sof', name: 'Science Olympiad Foundation', url: 'https://sofworld.org/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'olympiad', region: 'national', enabled: true },
  { id: 'silverzone', name: 'SilverZone Olympiads', url: 'https://silverzone.org/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'national', enabled: true },
  { id: 'unified-council', name: 'Unified Council Olympiads', url: 'https://www.unifiedcouncil.com/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'national', enabled: true },
  { id: 'crest-olympiads', name: 'CREST Olympiads', url: 'https://www.crestolympiads.com/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'olympiad', region: 'national', enabled: true },

  // ═══ Sports ═══
  { id: 'sgfi', name: 'School Games Federation India', url: 'https://sgfi.org.in/', strategy: 'cheerio', priority: 'high', scanInterval: 48, category: 'sports', region: 'national', enabled: true },
  { id: 'khelo-india', name: 'Khelo India', url: 'https://kheloindia.gov.in/', strategy: 'puppeteer', priority: 'critical', scanInterval: 24, category: 'sports', region: 'national', enabled: true },
  { id: 'sai', name: 'Sports Authority of India', url: 'https://sportsauthorityofindia.nic.in/', strategy: 'cheerio', priority: 'high', scanInterval: 48, category: 'sports', region: 'national', enabled: true },
  { id: 'cbse-sports', name: 'CBSE Sports', url: 'https://cbseacademic.nic.in/sports.html', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'sports', region: 'national', enabled: true },

  // ═══ Science & Innovation ═══
  { id: 'vigyan-prasar', name: 'Vigyan Prasar', url: 'https://vigyanprasar.gov.in/', strategy: 'cheerio', priority: 'medium', scanInterval: 48, category: 'academic', region: 'national', enabled: true },

  // ═══ Corporate Scholarships ═══
  { id: 'tata-trusts', name: 'Tata Trusts Education', url: 'https://www.tatatrusts.org/our-work/education', strategy: 'cheerio', priority: 'medium', scanInterval: 72, category: 'scholarship', region: 'national', enabled: true },
  { id: 'adanifoundation', name: 'Adani Foundation Education', url: 'https://www.adanifoundation.org/education', strategy: 'cheerio', priority: 'medium', scanInterval: 72, category: 'scholarship', region: 'national', enabled: true },
  { id: 'infosys-foundation', name: 'Infosys Foundation', url: 'https://www.infosys.com/infosys-foundation/', strategy: 'cheerio', priority: 'low', scanInterval: 72, category: 'scholarship', region: 'national', enabled: true },

  // ═══ Internship ═══
  { id: 'internshala', name: 'Internshala', url: 'https://internshala.com/internships/', strategy: 'cheerio', priority: 'high', scanInterval: 24, category: 'internship', region: 'national', enabled: true },
];

// ─── Removed SEARCH_QUERIES (Google News) as we now use OFFICIAL_RSS_FEEDS ───

// ─── Helper Functions ───

function getSourcesByPriority(priority) {
  return SOURCES.filter(s => s.enabled && s.priority === priority);
}

function getSourcesByStrategy(strategy) {
  return SOURCES.filter(s => s.enabled && s.strategy === strategy);
}

function getSourcesByRegion(region) {
  return SOURCES.filter(s => s.enabled && (s.region === region || s.region === 'national' || s.region === 'international'));
}

function getSourceById(id) {
  return SOURCES.find(s => s.id === id);
}

function getAllEnabledSources() {
  return SOURCES.filter(s => s.enabled);
}

function getSourcesDueForScan(lastScanTimes = {}) {
  const now = Date.now();
  return SOURCES.filter(s => {
    if (!s.enabled) return false;
    const lastScan = lastScanTimes[s.id] || 0;
    const intervalMs = s.scanInterval * 60 * 60 * 1000;
    return (now - lastScan) >= intervalMs;
  }).sort((a, b) => {
    const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 };
    return (priorityOrder[a.priority] ?? 4) - (priorityOrder[b.priority] ?? 4);
  });
}

module.exports = {
  SOURCES,
  getSourcesByPriority,
  getSourcesByStrategy,
  getSourcesByRegion,
  getSourceById,
  getAllEnabledSources,
  getSourcesDueForScan,
};
